# Generated by Django 4.2.30 on 2026-09-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fund_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund_utilized_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.division')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='PurposeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('claimed_status', models.CharField(choices=[('done', 'Done'), ('partial', 'Partial'), ('not_done', 'Not Done')], max_length=20)),
                ('actual_status', models.CharField(choices=[('done', 'Done'), ('partial', 'Partial'), ('not_done', 'Not Done'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('claimed', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
