# Generated by Django 4.2.30 on 2026-09-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_beneficiary_address_beneficiary_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
