# Generated by Django 4.2.30 on 2026-09-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.beneficiary'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_status',
            field=models.CharField(choices=[('none', 'No Duplicate'), ('potential', 'Potential Duplicate'), ('confirmed', 'Confirmed Duplicate'), ('dismissed', 'Dismissed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
