# Generated by Django 4.2.30 on 2026-09-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_beneficiary_duplicate_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
