# Generated by Django 4.2.30 on 2026-09-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_beneficiary_pan_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_reference_number', models.CharField(max_length=100)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='disbursement_receipts/')),
                ('disbursed_date', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='projects.beneficiary')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='projects.project')),
            ],
        ),
    ]
