# Generated by Django 4.2.30 on 2026-09-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_funddisbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scheme_name',
            field=models.CharField(choices=[('AVYAY', 'Atal Vayo Abhyuday Yojana (AVYAY)'), ('NAPDDR', 'National Action Plan for Drug Demand Reduction (NAPDDR)'), ('SMILE', 'SMILE - Transgender/Beggary Rehabilitation'), ('ELDERLINE', 'Elder Helpline (Elderline)'), ('SWAVALAMBAN', 'Swavalamban Yojana'), ('DDRS', 'Deen Dayal Disabled Rehabilitation Scheme (DDRS)'), ('NATIONAL_TRUST', 'National Trust Schemes'), ('VAYOSHRI', 'Rashtriya Vayoshri Yojana'), ('SAGE', 'Seniorcare Ageing Growth Engine (SAGE)'), ('PM_AJAY', 'PM-AJAY (Pradhan Mantri Anusuchit Jaati Abhyuday Yojana)'), ('OTHER', 'Other / General')], default='OTHER', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('approved_quantity', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
        ),
    ]
