# Generated by Django 4.2.30 on 2026-09-09 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('fund_utilized_verified', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beneficiaries_claimed_count', models.IntegerField(default=0)),
                ('beneficiaries_verified_count', models.IntegerField(default=0)),
                ('ghost_beneficiaries_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('report_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('block_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.inspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lng', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.inspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fund_mismatch', 'Fund Mismatch'), ('ghost_beneficiary', 'Ghost Beneficiary'), ('attendance', 'Attendance'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.inspectionreport')),
            ],
        ),
    ]
