# Generated by Django 4.2.30 on 2026-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='type',
            field=models.CharField(choices=[('fund_mismatch', 'Fund Mismatch'), ('ghost_beneficiary', 'Ghost Beneficiary'), ('attendance', 'Attendance'), ('purpose_mismatch', 'Purpose Mismatch'), ('other', 'Other')], max_length=50),
        ),
    ]
