# Generated by Django 4.2.30 on 2026-09-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_anomaly_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
