# Generated by Django 4.2.30 on 2026-09-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_beneficiary_address_beneficiary_phone_number_and_more'),
        ('reports', '0003_alter_inspectionreport_findings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOPeriodicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('financial_utilization', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activity_details', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
