# Generated by Django 4.2.30 on 2026-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_ngoperiodicreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoperiodicreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Verified/Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
