# Generated by Django 4.2.30 on 2026-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_ngoperiodicreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='location_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='type',
            field=models.CharField(choices=[('fund_mismatch', 'Fund Mismatch'), ('ghost_beneficiary', 'Ghost Beneficiary'), ('attendance', 'Attendance'), ('purpose_mismatch', 'Purpose Mismatch'), ('location_mismatch', 'Location Mismatch'), ('other', 'Other')], max_length=50),
        ),
    ]
