# Generated by Django 4.2.30 on 2026-09-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_beneficiary_duplicate_of_and_more'),
        ('reports', '0006_evidence_location_flagged_alter_anomaly_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('findings', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='nss_photos/')),
                ('scheme_implementation_status', models.CharField(choices=[('proper', 'Properly Implemented'), ('partial', 'Partially Implemented'), ('not_implemented', 'Not Implemented')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nss_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nss_visits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nss_visits', to='projects.project')),
            ],
        ),
    ]
