# Generated by Django 4.2.30 on 2026-09-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_scheme_name_projectasset'),
        ('reports', '0007_nssvisitreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='cctv_last_record_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='cctv_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='compliance_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='final_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReportViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=20)),
                ('description', models.TextField()),
                ('corrective_deadline', models.DateField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='reports.inspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_rating', models.IntegerField(blank=True, null=True)),
                ('medical_rating', models.IntegerField(blank=True, null=True)),
                ('staff_rating', models.IntegerField(blank=True, null=True)),
                ('cleanliness_rating', models.IntegerField(blank=True, null=True)),
                ('safety_rating', models.IntegerField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reports.inspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('is_compliant', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='reports.inspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportBeneficiaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_notes', models.TextField(blank=True, null=True)),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.beneficiary')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_logs', to='reports.inspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_quantity', models.IntegerField(default=0)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('discrepancy_flag', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectasset')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_verifications', to='reports.inspectionreport')),
            ],
        ),
    ]
