# Generated by Django 4.2.30 on 2026-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_inspectionreport_cctv_last_record_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='client_submission_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ngoperiodicreport',
            name='client_submission_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
