# Generated by Django 4.2.30 on 2026-09-10 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection')),
                ('original_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('proposed_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
