# Generated by Django 4.2.30 on 2026-09-18 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0003_inspectorlocationping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='ringing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_direct_calls', to=settings.AUTH_USER_MODEL)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_direct_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
