# Generated by Django 4.2.30 on 2026-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionassignment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
