# Generated by Django 4.2.30 on 2026-09-20 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0006_inspectionassignment_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionassignment',
            name='jitsi_room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionassignment',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_official', to=settings.AUTH_USER_MODEL),
        ),
    ]
