# Generated by Django 4.2.30 on 2026-09-21 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0007_alter_inspectionassignment_jitsi_room_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomVerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('no_response', 'No Response'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('jitsi_room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('missed_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('vc_room_created_at', models.DateTimeField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_events', to='inspections.inspection')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_received', to=settings.AUTH_USER_MODEL)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_initiated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
